services:
  todo-list:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: todolist
      POSTGRES_DB: todolist_db